title: GeoDiscovery Documentation
description: Documentaiton for the GeoDiscovery project at the UWM Libraries American Geographical Society Library
theme: just-the-docs

url: https://uwm-libraries.github.io/GeoDiscovery-Documentation/

callouts:
  warning:
    title: Warning!
    color: red
  note:
    title: Note
    color: purple
  highlight:
    title: Tip
    color: yellow

aux_links:
  Documentation repo: https://github.com/UWM-Libraries/GeoDiscovery-Documentation
