title: GeoDiscovery Documentation
description: Documentaiton for the GeoDiscovery project at the UWM Libraries American Geographical Society Library
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
